[book]
title = "Higher-Order Typed Compilation"
author = "Cameron Wong transcribed from Karl Crary"
description = "A transcription of my lecture notes from 15-417"

[build]
build-dir = "docs/"
create-missing = true

[preprocessor.index]

[preprocessor.links]

[preprocessor.fixmath]
command = "fixmath/target/debug/fixmath"
renderer = ["html"]

[preprocessor.diagrammer]
command = "diagrammer/target/debug/diagrammer"
renderer = ["html"]

[output.html]
additional-css = []
mathjax-support = true

[output.html.search]
limit-results = 15

