[package]
name = "fixmath"
version = "0.1.0"
authors = ["Cameron Wong <cjwong@andrew.cmu.edu>"]
edition = "2018"

[dependencies]
mdbook = "0.3.5"
clap = "2.33.0"
pulldown-cmark = "0.6.1"
pulldown-cmark-to-cmark = "2.0.1"
serde_json = "1.0.46"
